import 'package:ansicolor/ansicolor.dart';
import 'package:flutter/material.dart';

enum Gender {
  male,
  female,
}

enum Nationality {
  au,
  br,
  ca,
  ch,
  de,
  dk,
  es,
  fi,
  fr,
  gb,
  ie,
  ir,
  nl,
  nz,
  tr,
  us,
}

enum Include {
  gender,
  name,
  location,
  email,
  login,
  registered,
  dob,
  phone,
  cell,
  id,
  picture,
  nat,
}

enum Exclude {
  gender,
  name,
  location,
  email,
  login,
  registered,
  dob,
  phone,
  cell,
  id,
  picture,
  nat,
}

class Filter {
  int? results;
  Gender? gender;
  List<Nationality>? nationality;
  int? page;
  List<Include>? include;
  List<Exclude>? exclude;

  Filter({
    this.results,
    this.gender,
    this.nationality,
    this.page,
    this.include,
    this.exclude,
  });

  Map<String, dynamic> toQueryParams() {
    final queryParams = <String, dynamic>{};

    if(include?.isNotEmpty == true && exclude?.isNotEmpty == true){
      throw Exception('>>>>>>>> You can only INCLUDE or EXCLUDE fields, not both. <<<<<<<<');
    }
    if((results ?? -1) < 0 && (results ?? -1) > 5000) {
      throw Exception('>>>>>>>> Results must be between 0 and 5000 <<<<<<<<');
    }

    /*
    * Requesting Multiple Users
    * Random User Generator allows you to fetch up to 5,000 generated users in one request using the results parameter.
    * https://randomuser.me/api/?results=5000
    * */
    if (results != null && (results ?? -1) > 0 && (results ?? -1) < 5000) {
      queryParams['results'] = results.toString();
    }

    /*
    * Specifying a gender
    * You can specify whether you would like to have only male or only female users generated by adding the gender parameter to your request. Valid values for the gender parameter are "male" or "female", or you may leave the parameter blank. Any other value will cause the service to return both male and female users.
    * https://randomuser.me/api/?gender=female
    * */
    if (gender != null) {
      queryParams['gender'] = gender?.name.toLowerCase();
    }

    /*
    * Nationalities
    *You can request a different nationality of a randomuser.
    *
    *Pictures won't be affected by this, but data such as location, cell/home phone, id, etc. will be more appropriate.
    *
    *Currently, randomuser offers these nationalities:
    *
    * v1.0: AU, BR, CA, CH, DE, DK, ES, FI, FR, GB, IE, IR, NL, NZ, TR, US
    * v1.1: AU, BR, CA, CH, DE, DK, ES, FI, FR, GB, IE, IR, NL, NZ, TR, US
    * v1.2: AU, BR, CA, CH, DE, DK, ES, FI, FR, GB, IE, IR, NO, NL, NZ, TR, US
    * v1.3: AU, BR, CA, CH, DE, DK, ES, FI, FR, GB, IE, IR, NO, NL, NZ, TR, US
    * v1.4: AU, BR, CA, CH, DE, DK, ES, FI, FR, GB, IE, IN, IR, MX, NL, NO, NZ, RS, TR, UA, US
    * You can specify a nationality like so:
    * https://randomuser.me/api/?nat=gb
    * Randomuser will return random nats by default. You can have some control with the nats that you'd like to have generated by specifying a comma seperated list:
    * https://randomuser.me/api/?nat=us,dk,fr,gb
    */
    if (nationality != null && nationality?.isNotEmpty == true) {
      queryParams['nat'] = nationality?.map((e) => e.name).join(',');
    }

    /*
    * You can request multiple pages of a seed with the page parameter.
    * Make sure that you use the same seed and page number (1 based index)
    * in order to get back the same results
    * https://randomuser.me/api/?page=3&results=10&seed=abc
    * */
    if (page != null) {
      // queryParams['page'] = page.toString();
      // TODO: Implement pagination
    }

    /*
    * Including/Excluding fields
    * Sometimes, maybe you want some random names and not extraneous data such as location, phone, etc.
    * Using the inc and exc parameters, you can specify which fields to include or exclude respectively.
    *
    * By specifying only the fields you want, the generator can save time by skipping CPU intensive fields like "login" for example.
    *
    * These parameters accept the following values in a comma delimited list
    *
    * gender
    * name
    * location
    * email
    * login
    * registered
    * dob
    * phone
    * cell
    * id
    * picture
    * nat
    * If you only wanted the names,genders,and nats of users:
    *
    * https://randomuser.me/api/?inc=gender,name,nat
    * If you want everything except for login data:
    *
    * https://randomuser.me/api/?exc=login
    * */
    if (include != null && include?.isNotEmpty == true) {
      queryParams['inc'] = include?.map((e) => e.name).join(',');
    }

    if (exclude != null && exclude?.isNotEmpty == true) {
      queryParams['exc'] = exclude?.map((e) => e.name).join(',');
    }

    return queryParams;
  }

  Filter copyWith({
    int? results,
    Gender? gender,
    List<Nationality>? nationality,
    int? page,
    List<Include>? include,
    List<Exclude>? exclude,
  }) {
    return Filter(
      results: results ?? this.results,
      gender: gender ?? this.gender,
      nationality: nationality ?? this.nationality,
      page: page ?? this.page,
      include: include ?? this.include,
      exclude: exclude ?? this.exclude,
    );
  }
}
